sudo: false
notifications:
  on_success: change
  on_failure: always
cache:
  apt: true
  directories:
  - node_modules
  - vendor
  - "$HOME/.composer/cache"
language:
- php
jobs:
  fast_finish: true
  allow_failures:
  - php: nightly
  include:
  - php: nightly
    env: WP_VERSION=master WP_MULTISITE=0
  - php: 7.1
    env: WP_VERSION=4.8-branch WP_MULTISITE=0 SNIFF=1
  - php: 7.0
    env: WP_VERSION=4.8-branch WP_MULTISITE=0
  - php: 5.6
    env: WP_VERSION=4.8-branch WP_MULTISITE=0
  - stage: deployment
    install: npm install
    before_script: skip
    script:
      - npm run build
      - ls -la
      - zip -r published.zip ./ -x=".*" -x="./_tests/*" -x="./_scripts/*" -x="./node_modules/*" -x="./vendor/*" -x="./composer.*" -x="./package*.json" -x="./phpcs.xml"
    deploy:
      provider: releases
      api_key:
        secure: eKvDiB+VpF15OqWsVCd+HgZDzsLiUOshVk3VSBv4VlzMycDBCsLsxDBgqzSImrZZcKz4aSiFuV9OA/ccenh4/rPdPTiUp9527fLmyjur3SnxxkJs3vKE/sHSYByH3xG+Mt8KMW6eciSU7M7cuhTUF8tVXybqBN97A8168v7b6gLYON/AQ0fhvcrK/XYqAfmKBMd6xjui3DsVQ/KDq6IHlIiRQQmZpaug9Nh/DHDp8YEx5ek2Kzjk5sQiejFmbdw037h7Y+TNOMtWXLK2HT3QNl8UTwhNHpDVzv5bcLBYlyPRUQoDNCx33rUHYTyB0113vXxCMEET9pYWtM7qQM5NYgbBhoY2c9IP3MTIaRKlgYDh17i6SMAKmT1PbQA3KNXsSJTQE0nsC84GH/qvwQ00/x7SlFxWaWI0MfHsi2wF0GcGrXIflVq0KS76ihq6rf3AI3OlfMAcFLVHV7UFLujCASVNqbISxeLEiXM6HV19eWPl9aId95wDWt+XmcojP588XKqb1eInL2ZLcCRY0yfMZg4ttusD39fN1VnJpaY7skfmQp2TKplWPfjX/nU1g4epwFK/MbXh6rLXL1yh8g3EjgyWeKMCyJrTELIo4m+SobC2kjcYmsrHrDfiNZeGWudOsS24OfCusi/wd4yOqXQfiM7bcTFPZ7IKwJ2Y0KItMpg=
      file: "./published.zip"
      skip_cleanup: true
      on:
        repo: michaelbragg/published
        tags: true

before_install:
- phpenv config-rm xdebug.ini
- nvm install 6.11
install:
- if [[ "$SNIFF" == "1" ]]; then npm install; fi
before_script:
- export WP_DEVELOP_DIR=/tmp/wordpress
- mkdir -p $WP_DEVELOP_DIR
- git clone --depth=1 --branch="$WP_VERSION" https://github.com/WordPress/WordPress.git
  $WP_DEVELOP_DIR
- export WP_THEME_SLUG=$(basename $(pwd))
- export WP_THEME_DIR=$WP_DEVELOP_DIR/wp-content/themes
- mkdir -p $WP_THEME_DIR
- cd ..
- mv $WP_THEME_SLUG $WP_THEME_DIR
- mysql -e "CREATE DATABASE wordpress;" -uroot
- if [[ "$SNIFF" == "1" ]]; then composer require thoughtsideas/ti-wpcs:^1.1.1; fi
script:
- if [[ "$SNIFF" == "1" ]]; then ./vendor/bin/phpcs $WP_THEME_DIR/$WP_THEME_SLUG/
  --standard=$WP_THEME_DIR/$WP_THEME_SLUG/phpcs.xml; fi
- if [[ "$SNIFF" == "1" ]]; then ./vendor/bin/phpmd $WP_THEME_DIR/$WP_THEME_SLUG/
  text ./vendor/thoughtsideas/ti-wpcs/TI-WPMD/ruleset.xml; fi
- if [[ "$SNIFF" == "1" ]]; then npm run build --prefix $WP_THEME_DIR/$WP_THEME_SLUG/;
  fi
