sudo: false

notifications:
  on_success: change
  on_failure: always

# Cache Composer's caches to speed up build times.
cache:
  directories:
    - $HOME/.composer/cache

language:
  - php

matrix:
  include:
    - php: nightly
      env: WP_VERSION=master WP_MULTISITE=0
    - php: 7.1
      env: WP_VERSION=master WP_MULTISITE=0
    - php: 7.0
      env: WP_VERSION=master WP_MULTISITE=0
    - php: 5.6
      env: WP_VERSION=master WP_MULTISITE=0
  allow_failures:
    - php: nightly

before_install:
  - phpenv config-rm xdebug.ini
  - nvm install 6.11

before_script:
    # Set up WordPress installation.
  - export WP_DEVELOP_DIR=/tmp/wordpress
  - mkdir -p $WP_DEVELOP_DIR
  # Use the Git mirror of WordPress.
  - git clone --depth=1 --branch="$WP_VERSION" https://github.com/WordPress/WordPress.git $WP_DEVELOP_DIR
  # Move plugin to WordPress directory.
  - export WP_THEME_SLUG=$(basename $(pwd))
  - export WP_THEME_DIR=$WP_DEVELOP_DIR/wp-content/themes
  - mkdir -p $WP_THEME_DIR
  # Move above our WordPress directory.
  - cd ..
  - mv $WP_THEME_SLUG $WP_THEME_DIR
  # Setup WordPress
  - mysql -e "CREATE DATABASE wordpress;" -uroot
  # Install composer packages before trying to activate themes or plugins
  - composer require thoughtsideas/ti-wpcs:*
  - vendor/bin/phpcs --config-set installed_paths ../../../vendor/wp-coding-standards/wpcs,../../../vendor/frenck/php-compatibility,../../../vendor/thoughtsideas/ti-wpcs
  - vendor/bin/phpcs --config-set default_standard TI-WPCS

script:
  - ./vendor/bin/phpcs $WP_THEME_DIR/$WP_THEME_SLUG/
  - ./vendor/bin/phpmd $WP_THEME_DIR/$WP_THEME_SLUG/ text ./vendor/thoughtsideas/ti-wpcs/TI-WPMD/ruleset.xml
