sudo: false

notifications:
  on_success: change
  on_failure: always

# Cache Composer's caches to speed up build times.
cache:
  apt: true
  directories:
    - node_modules
    - vendor
    - $HOME/.composer/cache

language:
  - php

matrix:
  include:
    - php: nightly
      env: WP_VERSION=master WP_MULTISITE=0
    - php: 7.1
      env: WP_VERSION=4.8-branch WP_MULTISITE=0 SNIFF=1
    - php: 7.0
      env: WP_VERSION=4.8-branch WP_MULTISITE=0
    - php: 5.6
      env: WP_VERSION=4.8-branch WP_MULTISITE=0
  allow_failures:
    - php: nightly
  fast_finish: true

before_install:
  - phpenv config-rm xdebug.ini
  - nvm install 6.11

install:
  - if [[ "$SNIFF" == "1" ]]; then npm install; fi

before_script:
    # Set up WordPress installation.
  - export WP_DEVELOP_DIR=/tmp/wordpress
  - mkdir -p $WP_DEVELOP_DIR
  # Use the Git mirror of WordPress.
  - git clone --depth=1 --branch="$WP_VERSION" https://github.com/WordPress/WordPress.git $WP_DEVELOP_DIR
  # Move plugin to WordPress directory.
  - export WP_THEME_SLUG=$(basename $(pwd))
  - export WP_THEME_DIR=$WP_DEVELOP_DIR/wp-content/themes
  - mkdir -p $WP_THEME_DIR
  # Move above our WordPress directory.
  - cd ..
  - mv $WP_THEME_SLUG $WP_THEME_DIR
  # Setup WordPress
  - mysql -e "CREATE DATABASE wordpress;" -uroot
  # Install composer packages before trying to activate themes or plugins
  - if [[ "$SNIFF" == "1" ]]; then composer require thoughtsideas/ti-wpcs:^1.1.1; fi

script:
  # Only run PHP Code tests on one environment to improve total test time.
  - if [[ "$SNIFF" == "1" ]]; then ./vendor/bin/phpcs $WP_THEME_DIR/$WP_THEME_SLUG/ --standard=$WP_THEME_DIR/$WP_THEME_SLUG/phpcs.xml; fi
  - if [[ "$SNIFF" == "1" ]]; then ./vendor/bin/phpmd $WP_THEME_DIR/$WP_THEME_SLUG/ text ./vendor/thoughtsideas/ti-wpcs/TI-WPMD/ruleset.xml; fi
#  - if [[ "$SNIFF" == "1" ]]; then npm test --prefix $WP_THEME_DIR/$WP_THEME_SLUG/; fi
  - if [[ "$SNIFF" == "1" ]]; then npm run build --prefix $WP_THEME_DIR/$WP_THEME_SLUG/; fi
