#!/bin/sh
#
# Quality Assurance tests

# Run tests
echo "Running WordPress PHP Coding Standards test"
composer run test-phpcbf
composer run test-phpcs
# PHPCS Results (bool)
QA_PHPCS=$?

echo "Running WordPress PHP Mess Detector test"
composer run test-phpmd
# PHPMD Results (bool)
QA_PHPMD=$?

echo "Running WordPress PHP Copy Paste Detector test"
composer run test-phpcpd
# PHPCPD Results (bool)
QA_PHPCPD=$?

echo "Running WordPress PHP Security Checker test"
composer run test-phpsc
# PHPSC Results (bool)
QA_PHPSC=$?

echo "Running WordPress PHP Magic Number Detector test"
composer run test-phpmnd
# PHPMND Results (bool)
QA_PHPMND=$?

[ $QA_PHPCS -ne 0 ] && exit 1
[ $QA_PHPMD -ne 0 ] && exit 1
[ $QA_PHPCPD -ne 0 ] && exit 1
[ $QA_PHPSC -ne 0 ] && exit 1
[ $QA_PHPMND -ne 0 ] && exit 1

# If test pass exit successfully.
exit 0
